

export interface Category {
	id:               number;
	nombre:           string;
	esPrivada:        boolean;
	usuarioCreadorId: number;
	createdDate:      string;
	lastUpdate:       string;
}

// Generated by https://quicktype.io

export interface CategoriesFilterRequest {
	idUsuarioCreador: number;
	nombre?:           string;
	esPrivada?:        boolean;
}

