// Generated by https://quicktype.io

export interface ShoppingListsResponse {
    status: number;
    body:   ShoppingList[];
    message?: string;
}

export interface CreateShoppingListResponse {
    status: number;
    body:   ShoppingList;
    message?: string;
}

export interface ShoppingList {
    id:              number;
    nombre:          string;
    estado:          string;
    fechaCreacion:   string;
    fechaFinalizado?: string;
    totalCompras:    string;
    usuarioCreador:  number;
    codigoGenerado:  string;
}

// Generated by https://quicktype.io

export interface CreateShoppingListRequest {
    nombre:         string;
    usuarioCreador: number;
}



