// Generated by https://quicktype.io

export interface ShoppingListsResponse {
    status: number;
    body:   ShoppingList[];
}

export interface ShoppingList {
    id:              number;
    nombre:          string;
    estado:          string;
    fechaCreacion:   string;
    fechaFinalizado?: string;
    totalCompras:    string;
    usuarioCreador:  number;
    codigoGenerado:  string;
}
