// Generated by https://quicktype.io

// Generated by https://quicktype.io

export interface UserLoginRequest {
    correo: string;
    pass:   string;
}


export interface UserLoggedResponse {
    status: number;
    body:   User;
}

export interface User {
    id:         number;
    nombres:    string;
    apellidos:  string;
    activo:     boolean;
    correo:     string;
    contrasena: string;
}

// Generated by https://quicktype.io

export interface CollaboratorsFilterRequest {
    idListaCompras: number;
    estados:        string[];
    nombres?:        string;
}


// Generated by https://quicktype.io

export interface CollaboratorsFilterResponse {
    status: number;
    body:   Collaborator[];
}

export interface Collaborator {
    id:               number;
    porcentaje:       string;
    estado:           string;
    nombresUsuario:   string;
    apellidosUsuario: string;
    idListaCompra:    number;
    idUsuario:        number;
    esCreador:        boolean;
}

