// Generated by https://quicktype.io

// Generated by https://quicktype.io

export interface UserLoginRequest {
    correo: string;
    pass:   string;
}


export interface UserLoggedResponse {
    status: number;
    body:   User;
}

export interface User {
    id:         number;
    nombres:    string;
    apellidos:  string;
    activo:     boolean;
    correo:     string;
    contrasena: string;
}
