// Generated by https://quicktype.io

// Generated by https://quicktype.io

export interface UserLoginRequest {
    email: string;
    pass:   string;
}


export interface UserLoggedResponse {
    status: number;
    body:   User;
}

export interface User {
    id:         number;
    nombres:    string;
    apellidos:  string;
    activo:     boolean;
    correo:     string;
    contrasena: string;
}

// Generated by https://quicktype.io

export interface CollaboratorsFilterRequest {
    idListaCompras: number;
    estados?:        string[];
    nombres?:        string;
}


// Generated by https://quicktype.io

export interface CollaboratorsFilterResponse {
    status: number;
    body:   Collaborator[];
}

export interface Collaborator {
    id:               number;
    porcentaje:       number;
    estado:           string;
    nombres:          string;
    apellidos:        string;
    idListaCompra:    number;
    idUsuario:        number;
    esCreador:        boolean;
}


export interface CollaboratorsParams {
    idListaCompras?: number;
    idUsuarioCreador?: number;
    estadoLista?: string;
    porcentaje?: number;
    
}

export interface AssignPercentageParams {
    collaborator: Collaborator;
    idUsuarioCreador: number;
}

// HABILITAR O NO COLABORADOR

// Generated by https://quicktype.io

export interface ApproveRejectCollaboratorRequest {
    idUsuarioCreador:     number;
    idUsuarioColaborador: number;
    idListaCompras:       number;
    aprobar:              boolean;
}


// Generated by https://quicktype.io

export interface AssignPercentageCollaboratorRequest {
    idUsuarioCreador:     number;
    idUsuarioColaborador: number;
    idListaCompras:       number;
    porcentaje:           number;
}




